---

- include_vars: openmpi_vars.yml

- name: Install openmpi requirements on RedHat, CentOS or SL
  yum: name={{item}} state=present
  with_items: "{{openmpi_requirements_redhat}}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Scientific' or ansible_distribution == 'RedHat'
  vars:
  
- name: Install openmpi requirements on Fedora
  dnf: name={{item}} state=present
  with_items: "{{openmpi_requirements_redhat}}"
  when: ansible_distribution == 'Fedora'
  vars:
  
- name: Install build tools on Ubuntu
  apt: name={{item}} state=present update_cache=yes
  with_items: "{{openmpi_requirements_ubuntu}}"
  when: ansible_distribution == 'Ubuntu'

- name: Download OpenMPI
  get_url: url={{openmpiinfo['url']}} dest="{{source_download_dir}}/{{openmpiinfo['filename']}}"

- name: Template the install script
  template: src=openmpi.sh dest="{{install_scripts_dir}}/openmpi.sh" owner=root mode=0700 backup=no
  
- name: Execute the openmpi.sh script
  shell: "{{install_scripts_dir}}/openmpi.sh"
  args:
    creates: "{{build_anchors}}/openmpibuild.log"
    
- name: Add OpenMPI to PATH
  template: src=openmpi_path.sh dest=/etc/profile.d/openmpi_path.sh mode=0644 backup=no owner=root
    
- name: Link OpenMPI build
  lineinfile:
    path: /etc/ld.so.conf.d/openmpi.conf
    create: yes
    state: present
    regexp: ^{{openmpiinfo['prefix']}}
    line: "{{openmpiinfo['prefix']}}/lib"
  notify: Link libraries
  
...
 
