---

- include_vars: R_vars.yml

- name: Install R YUM
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{R_system_packages_redhat}}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Scientific'

- name: Install R DNF
  dnf:
    name: "{{item}}"
    state: present
  with_items: "{{R_system_packages_redhat}}"
  when: ansible_distribution == 'Fedora'
  
# Thanks: https://adamj.eu/tech/2014/07/19/installing-and-removing-r-packages-with-ansible/
- name: Install additional R packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('http://ftp.heanet.ie/mirrors/cran.r-project.org/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items: "{{R_additional}}"
    
...
