---

- include_vars: slurm_vars.yml

  #Create credentials
- name: SLURM group
  group: name=slurm state=present system=yes
- name: SLURM user
  user: name=slurm createhome=yes comment="SLURM workload manager" group=slurm home=/var/lib/slurm shell=/sbin/nologin state=present system=yes
  
  #Install prerequisites
- name: Install prerequisites YUM
  yum: name={{item}} state=present
  with_items: "{{slurm_packages_redhat}}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Scientific' or ansible_distribution == 'RedHat'
- name: Install prerequisites DNF
  dnf: name={{item}} state=present
  with_items: "{{slurm_packages_redhat}}"
  when: ansible_distribution == 'Fedora'
- name: Install prerequisites APT
  apt: name={{item}} state=present
  with_items: "{{slurm_packages_ubuntu}}"
  when: ansible_distribution == 'Ubuntu'
  
  #Download and compile slurm
- name: Download slurm
  get_url: 
    url: "{{slurminfo['url']}}"
    dest: "{{source_download_dir}}/{{slurminfo['filename']}}"
- name: Template the slurm script
  template:
    src: slurm.sh
    dest: "{{install_scripts_dir}}/slurm.sh"
    owner: root
    group: root
    mode: 0744
    backup: no
- name: Execute the slurm script
  shell: "{{install_scripts_dir}}/slurm.sh"
  args:
    creates: "{{build_anchors}}/slurmbuild.log"
    
- name: Create slurm sysconfdir
  file:
    path: "{{slurminfo['sysconfdir']}}"
    state: directory
    mode: 0755
    
- name: Copy slurm example configs to sysconfdir
  copy:
    src: "{{item}}"
    dest: "{{slurminfo['sysconfdir']}}"
    mode: 0644
  with_items:
    - cgroup_allowed_devices_file.conf.example
    - cgroup.conf.example
    - slurm.conf.example
    - slurmdbd.conf.example
    
- name: Template the slurm.epilog to sysconfdir
  template: src=slurm.epilog.clean dest="{{slurminfo['sysconfdir']}}/slurm.epilog.clean" mode=0755
    
- name: Create layouts subdir
  file:
    path: "{{slurminfo['sysconfdir']}}/layouts.d"
    state: directory
    mode: 0755
    
- name: Copy slurm example layouts
  copy:
    src: "{{item}}"
    dest: "{{slurminfo['sysconfdir']}}/layouts.d"
    mode: 0644
  with_items:
    - power.conf.example
    - power_cpufreq.conf.example
    - unit.conf.example
  
- name: Add Slurm to PATH
  template: src=slurm_path.sh dest=/etc/profile.d/slurm_path.sh mode=0644 backup=no owner=root
    
- name: Link Slurm build
  lineinfile:
    path: /etc/ld.so.conf.d/slurm.conf
    create: yes
    state: present
    regexp: ^{{slurminfo['prefix']}}
    line: "{{slurminfo['prefix']}}/lib"
  notify: Link libraries
    
...
