---

  #Create credentials
- name: SLURM group
  group: name=slurm gid=395 state=present system=yes
- name: SLURM user
  user: name=slurm createhome=yes uid=395 comment="SLURM workload manager" group=slurm home=/var/lib/slurm shell=/sbin/nologin state=present system=yes
  
  #Install prerequisites
- name: Install prerequisites YUM
  yum: name={{item}} state=present
  with_items: "{{slurm_packages_redhat}}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Scientific'
- name: Install prerequisites DNF
  dnf: name={{item}} state=present
  with_items: "{{slurm_packages_redhat}}"
  when: ansible_distribution == 'Fedora'
- name: Install prerequisites APT
  apt: name={{item}} state=present
  with_items: "{{slurm_packages_ubuntu}}"
  when: ansible_distribution == 'Ubuntu'
  
  #Download and compile slurm
- name: Download slurm
  get_url: 
    url: "{{slurminfo['url']}}"
    dest: "{{source_download_dir}}/{{slurminfo['filename']}}"
- name: Template the slurm script
  template:
    src: slurm.sh
    dest: "{{install_scripts_dir}}/slurm.sh"
    owner: root
    group: root
    mode: 0744
    backup: no
- name: Execute the slurm script
  shell: "{{install_scripts_dir}}/slurm.sh"
  args:
    creates: "{{build_anchors}}/slurmbuild.log"
  register: slurm_installation
  
- name: Reload systemd daemons if needed
  systemd:
    daemon_reload: yes
    
...
