---

- name: Install prerequisites on Ubuntu based systems
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{infiniband_packages_debian}}"

- name: Template the interfaces file for Ubuntu
  template:
    src: ubuntu_network_interfaces
    dest: /etc/network/interfaces
    mode: 0644
    backup: yes
  notify: Restart network
  
- name: Enable and start rdma modules
  modprobe:
    name: "{{item}}"
    state: present
  with_items:
    - rdma_cm
    - ib_uverbs
    - ib_ucm
    - ib_umad
    - ib_ipoib
    - mlx_ib
    - mlx4_en
    - iw_cxgb3
    - iw_cxgb4
    - iw_nes
    - iw_c2
  
...
