---

### Main tasks for frontend on CentOS, Redhat or Scientific

- name: Check for frontend OS
  fail: msg="You need to use a CentOS, SL or RedHat system"
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Scientific' and ansible_distribution != 'RedHat'
- name: Check for OS version
  fail: msg="Please use a version >= 7"
  when: ansible_distribution_major_version != "7"
  
- include: ../../../playbooks/load_config.yml
  
- name: Install opensm and rdma
  yum: name={{item}} state=present
  with_items:
    - opensm
    - rdma
  
- name: Template the opensm config
  template: src=rdma_partitions dest=/etc/rdma/partitions.conf mode=0644 backup=yes
  notify: Restart opensm
  
- name: Enable and start opensm service
  service: name=opensm state=started enabled=yes

...
