---

#- name: Enable IPv4 forwarding
#  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
#- name: Enable bridge calls to iptables
#  sysctl: name={{item}} value=0 sysctl_set=yes state=present reload=yes
#  with_items:
#    - "net.bridge.bridge-nf-call-ip6tables"
#    - "net.bridge.bridge-nf-call-iptables"
#    - "net.bridge.bridge-nf-call-arptables"
#- name: Check for running firewalld
#  service: name=firewalld state=started

  #Insert direct rules for forwarding
#- name: Masquerade external interface
#  command: firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -o eth1 -j MASQUERADE
#- name: Forward internal->external
#  command: firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i eth0 -o eth1 -j ACCEPT
#- name: Forward external->internal
#  command: firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT

  #Map and source interfaces
- name: Map internal interface
  firewalld: zone=internal permanent=true interface=eth0 state=enabled
  notify: Restart firewalld
- name: Map external interface
  firewalld: zone=public permanent=true interface=eth1 state=enabled
  notify: Restart firewalld
- name: Add source IPs
  firewalld: zone=external source='{{ip_startaddress_external}}/{{netmask_external}}' state=enabled permanent=true
  notify: Restart firewalld
  
  #Security
- name: Masquerade external zone
  firewalld: zone=external masquerade=yes permanent=true state=enabled
  notify: Reload firewall rules
- name: Remove ssh access from public zone
  firewalld: zone=public service=ssh permanent=true state=disabled
  notify: Reload firewall rules
- name: Disable ICMP timestamps
  shell: firewall-cmd --add-icmp-block={{item}} --permanent
  with_items:
    - "timestamp-request"
    - "timestamp-reply"
  
  #Enable/open services and ports
- name: Enable services intern
  firewalld: service={{item}} permanent=true state=enabled zone=internal
  with_items: "{{firewall_services_eth0}}"
  notify: Reload firewall rules
- name: Enable services public
  firewalld: service={{item}} permanent=true state=enabled zone=public
  with_items: "{{firewall_services_eth1}}"
  notify: Reload firewall rules
- name: Enable services for source
  firewalld: service={{item}} permanent=true state=enabled zone=external
  with_items: "{{firewall_services_source}}"
  notify: Reload firewall rules
- name: Open up ports intern
  firewalld: port={{item}} permanent=true state=enabled zone=internal
  with_items: "{{firewall_ports_eth0}}"
  notify: Reload firewall rules
- name: Open up ports public
  firewalld: port={{item}} permanent=true state=enabled zone=public
  with_items: "{{firewall_ports_eth1}}"
  notify: Reload firewall rules
- name: Open up ports for source
  firewalld: port={{item}} permanent=true state=enabled zone=external
  with_items: "{{firewall_ports_source}}"
  notify: Reload firewall rules

...
