---

- name: Template the second interface
  template: src=ifcfg_eth1 dest=/etc/sysconfig/network-scripts/ifcfg-{{eth1_name}} mode=0644 backup=yes
  register: config_second_interface

- name: Template the first interface
  template: src=ifcfg_eth0 dest=/etc/sysconfig/network-scripts/ifcfg-{{eth0_name}} mode=0644 backup=yes
  register: config_first_interface
  
- name: Add static route for first interface
  lineinfile: dest=/etc/sysconfig/network-scripts/route-{{eth0_name}} regexp="^10" line="{{ip_startaddress_internal}}/{{netmask_internal}} via {{hostvars[groups['frontend'][0]]['eth0']}} dev {{eth0_name}}" state=present create=yes 
  register: first_interface_static_route
  
- name: Reactivate first interface if needed
  shell: ifdown {{eth0_name}} && ifup {{eth0_name}}
  when: config_first_interface.changed or first_interface_static_route.changed
  
- name: Activate second interface
  shell: ifdown {{eth1_name}} && ifup {{eth1_name}}
  when: config_second_interface.changed

...
