---

- include_vars: packages.yml

- name: Install ganglia per yum
  yum: name={{item}} state=present
  with_items: "{{ganglia_server_packages}}"
  
  #Copy config files
- name: Copy gmetad.conf
  template: src=gmetad.conf dest=/etc/ganglia/gmetad.conf owner=root mode=0644 backup=yes
  register: gmetad_config
- name: Template gmond.conf
  template: src=gmond.conf dest=/etc/ganglia/gmond.conf owner=root mode=0644 backup=yes
  register: gmond_config
  
- name: Set correct ownership for ganglia rrds
  file: path=/var/lib/ganglia/rrds state=directory owner=ganglia group=ganglia recurse=yes
  
- name: Restart gmond if changed
  service: name=gmond state=restarted
  when: gmond_config.changed
- name: Restart gmetad if changed
  service: name=gmetad state=restarted
  when: gmetad_config.changed

...
