---

- name: Install nfs-utils
  yum: name=nfs-utils state=present
  
- name: Mount homes at a fixed point
  mount:
    path: "{{homes_mountpoint_frontend}}"
    src: "{{groups['home_server'][0]}}:{{hostvars[groups['home_server'][0]]['home_export']}}"
    fstype: auto
    state: mounted
#TODO: Support NetworkManager so that systemd.after works
    opts: defaults,nofail,x-systemd.after=network-online.target
    
...
