---

- name: Install ntp
  yum: name=ntp state=present

- name: Template the ntp server config
  template: src=ntp-server.conf dest=/etc/ntp.conf owner=root group=root mode=0644 backup=yes
  notify: Restart ntpd
  
- name: Ensure stopped and disabled chronyd
  service: name=chronyd state=stopped enabled=no

...
