---

- name: Install autofs and nfs tools on CentOS or Scientific
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{autofs_packages_redhat}}"
  when: ansible_distribution != "Fedora"
  
- name: Install autofs and nfs tools on Fedora
  dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{autofs_packages_redhat}}"
  when: ansible_distribution == "Fedora"
  
...
