---

  #Copy and template kickstarts, scripts, snippets and sources
- name: Template kickstarts
  template: src={{item}} dest=/var/lib/cobbler/kickstarts/{{item | basename}}
  with_fileglob: kickstarts/*
  notify: Sync cobbler
- name: Template scripts
  template: src={{item}} dest=/var/lib/cobbler/scripts/{{item | basename}}
  with_fileglob: scripts/*
  notify: Sync cobbler
- name: Template snippets
  template: src={{item}} dest=/var/lib/cobbler/snippets/{{item | basename}}
  with_fileglob: snippets/*
  notify: Sync cobbler
  
- name: Copy sources
  copy: src={{item}} dest=/var/www/sources/{{item | basename}}
  with_fileglob: sources/*
  notify: Sync cobbler

...
