---

# This role sets up the cobbler profiles, downloads the distro isos,
# imports the distros into cobbler and creates repo mirrors
- include_vars: ../../../config.yml

- name: Check for frontend OS
  fail: msg="You need to use a CentOS, SL or RedHat system"
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Scientific' and ansible_distribution != 'RedHat'
- name: Check for OS version
  fail: msg="Please use a version >= 7"
  when: ansible_distribution_major_version != "7"
  
- include: cobbler_repos.yml
- include: cobbler_distros.yml
- include: cobbler_profiles.yml

...
