---

- name: Install ganglia per yum
  yum: name={{item}} state=present
  with_items: "{{ganglia_server_packages}}"
  
  #Copy config files
- name: Copy gmetad.conf
  template: src=gmetad.conf dest=/etc/ganglia/gmetad.conf owner=root mode=0644 backup=yes
  notify: Restart gmetad
- name: Template gmond.conf
  template: src=gmond_server.conf dest=/etc/ganglia/gmond.conf owner=root mode=0644 backup=yes
  notify: Restart gmond
- name: Copy ganglia.conf for httpd
  copy: src=ganglia.conf dest=/etc/httpd/conf.d/ganglia.conf mode=0644 backup=yes
  notify: Restart httpd
  
- name: Set correct ownership for ganglia rrds
  file: path=/var/lib/ganglia/rrds state=directory owner=ganglia group=ganglia recurse=yes
  
- name: Start and enable ganglia
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
    - gmond
    - gmetad

...
