---

#Cluster information
clustername: hpcnet
organization: HPC
fullname: High Performance Computing
webpage: "https://en.wikipedia.org/wiki/Supercomputer"
email: "example@hpc"

#Frontend config
###openssl passwd -1, for the super-secure password 'testpassword1234'
###needed for cobbler on system creation
root_password_md5: $1$Oy507HgT$/BGDUsFA/QX2VnyFOoEZA0
##For ssh key distribution, frontend -> nodes
root_ssh_publickey: "<INSERT-SSH-PKEY-HERE>"

#Define, where the shared applications coming from app_server will be mounted
appsdir: /opt/apps
homes_mountpoint_frontend: /mnt/homes

#localization
timezone: "US/Central"
lang: "en_US.utf8"
country: "GMT"
locale: "en"
keyboard_map: "us"

#network config
ip_startaddress_internal: 10.0.0.0
ip_startaddress_external: 192.168.1.0
dhcp_start_address: 10.0.100.1
dhcp_end_address: 10.0.100.200
netmask_internal: 16
netmask_internal_long: 255.255.0.0
netmask_external: 24
netmask_external_long: 255.255.255.0
main_gateway: 192.168.1.1
dns1: 208.67.222.222
dns2: 208.67.220.220
domain: mydomain.net

#Infiniband config
ibip_base: 10.1.1.0
ib_netmask: 16
ib_broadcast: 10.2.2.255
##possible rates: 2 to 10, 3==10GBit/s, 7 == 40GBit/s
ib_rate: 3
ib8002_rate: 7
##possible mtu's: 1 to 5, 4 == 2048
ib_mtu: 4
ib8002_mtu: 4
ibifcfg_mtu: 65520
ibifcfg_connected: yes #yes or no

#For webserver
ssl_files:
  official:
# Paths are relative to the tasks dir of webserver role
    cert: {src: "../../../webserver_cert/cert.pem", dest: "/etc/pki/tls/certs/cert.pem", config_prefix: "SSLCertificateFile"}
    key: {src: "../../../webserver_cert/HPC.KEY", dest: "/etc/pki/tls/private/HPC.KEY", config_prefix: "SSLCertificateKeyFile"}
    chain: {src: "../../../webserver_cert/chain.pem", dest: "/etc/pki/tls/certs/chain.pem", config_prefix: "SSLCertificateChainFile"}
  self:
    cert: {src: "", dest: "/etc/pki/tls/certs/apache_self.crt", config_prefix: "SSLCertificateFile"}
    key: {src: "", dest: "/etc/pki/tls/private/apache_self.key", config_prefix: "SSLCertificateKeyFile"}

slurmdbd_config:
  storageloc: slurm_acct_db #optional dbname, this value is default
  storagepass: testpassword #for slurmd/slurmctld munge will be used, this password is for slurmdbd and mysql itself
  storageuser: hpc
  rootpass: rootdatabasepw  #for slurmdbd itself, slurmd/slurmctld should use munge
  port: 6819                #optional port for slurmdbd, this value is default

zabbix_db_config:
#  username: zabbix #is default
  password: testpwINSECURE
#  dbname: zabbix_clustername #is default

...
