---

# The partitions present in the cluster
# DEFAULT means all
# highprio is an example for jobs with higher priority, suspending
# lower priority jobs

slurm_partitions:
  DEFAULT:
    nodes: "compute[01-04]"
    settings: "OverSubscribe=FORCE:1"
  common:
    nodes: "compute[01-04]"
    settings: "PriorityTier=1 Default=YES State=Up"
  gpu:
    nodes: "computeib"
    settings: "PriorityTier=1 Default=NO State=Up"
  highprio:
    nodes: "compute[01-02]"
    settings: "PriorityTier=2 Default=NO State=Up"

...
