---

- name: Add frontend hostnames to /etc/hosts
  lineinfile:
    line: "{{hostvars[groups['frontend'][0]]['eth0']}}    {{groups['frontend'][0]}} {{groups['frontend'][0]}}.{{clustername}}"
    regexp: ^{{hostvars[groups['frontend'][0]]['eth0']}}
    state: present

...
