---
  
- include: ../../../playbooks/load_slurm_partitions.yml
- include_vars: ../../software/vars/slurm_vars.yml
  
- name: Template the slurmd unit file
  template:
    src: slurmd.service
    dest: /usr/lib/systemd/system/slurmd.service
    owner: root
    mode: 0644
  notify: Reload systemd units
  
  #Copy Config
- name: Template the slurm.conf
  template: src=slurm.conf dest="/etc/slurm/slurm.conf" owner=root group=root mode=0644
  notify: Restart slurmd
  
  #Create dirs and set permissions
- name: Create slurm directories in /var/spool
  file: path=/var/spool/slurmd state=directory owner=slurm group=slurm mode=0755
- name: Create /var/run/slurm
  file: path=/var/run/slurm state=directory owner=slurm group=slurm mode=0755
- name: Create slurm log dir
  file: path=/var/log/slurm state=directory owner=slurm group=slurm mode=0755
  
- name: Start and enable slurmd
  service: name=slurmd state=started enabled=yes

...
