---
  
- include: ../../../playbooks/load_slurm_partitions.yml
- include_vars: ../../software/vars/slurm_vars.yml
  
- name: Template the slurmd unit file
  template:
    src: slurmd.service
    dest: /usr/lib/systemd/system/slurmd.service
    owner: root
    mode: 0644
  notify: Reload systemd units
  
- meta: flush_handlers

- name: Template the cgroup.conf
  template: src=cgroup.conf dest="/etc/slurm/cgroup.conf" owner=root group=root mode=0644
  notify: Restart slurmd
  
  #Copy Config
- name: Template the slurm.conf
  template: src=slurm.conf dest="/etc/slurm/slurm.conf" owner=root group=root mode=0644
  notify: Restart slurmd
  
  #Create dirs and set permissions
- name: Create slurm directories in /var/spool
  file: path=/var/spool/slurmd state=directory owner=root group=root mode=0755
- name: Create /var/run/slurm
  file: path=/var/run/slurm state=directory owner=root group=root mode=0755
- name: Create slurm log dir
  file: path=/var/log/slurm state=directory owner=root group=root mode=0755
  
- name: Tell systemd to create /var/run/slurm
  lineinfile:
    path: "/usr/lib/tmpfiles.d/slurm.conf"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    create: yes
    state: present
  with_items:
    - {regexp: "^d /var", line: "d /var/run/slurm  755 root root"}
  notify: Restart slurmd
  
- name: Start and enable slurmd
  service: name=slurmd state=started enabled=yes

...
