---

- name: Install needed Xorg packages YUM
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{xorg_packages_redhat}}"
  when: ansible_distribution != 'Fedora'
  
- name: Install needed Xorg packages DNF
  dnf:
    name: "{{item}}"
    state: present
  with_items: "{{xorg_packages_redhat}}"
  when: ansible_distribution == 'Fedora'

...
