---

- include_vars: ../../../config.yml

  #Template the slurm config
- name: Template the slurm.conf
  template: src=../../../slurm.conf dest="/etc/slurm/slurm.conf" owner=root group=root mode=0644
  register: slurm_config

...
