---

- include: ../../../playbooks/load_config.yml
- include: ../../../playbooks/load_slurm_partitions.yml

  #Template the slurm config
- name: Template the slurm.conf
  template: src=slurm.conf dest="/etc/slurm/slurm.conf" owner=root group=root mode=0644
  register: slurm_config
  
- name: Template the second interface
  template: src=ifcfg_eth1 dest=/etc/sysconfig/network-scripts/ifcfg-{{eth1_name}} mode=0644 backup=no
  register: config_second_interface
  
- name: Set default route
  lineinfile:
    path: /etc/sysconfig/network
    regexp: ^GATEWAY
    line: "GATEWAY={{main_gateway}}"
    create: yes
    state: present
  register: default_route
  
- name: Set internal interface defroute to no
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{eth0_name}}
    regexp: ^DEFROUTE
    line: "DEFROUTE=no"
    create: yes
    state: present
  register: config_first_interface
  
- name: Restart network if needed
  service:
    name: network
    state: restarted
  when: config_first_interface.changed or config_second_interface.changed default_route.changed

...
