---

- include: ../../../playbooks/load_config.yml
- include: ../../../playbooks/load_slurm_partitions.yml

  #Template the slurm config
- name: Template the slurm.conf
  template: src=slurm.conf dest="/etc/slurm/slurm.conf" owner=root group=root mode=0644
  register: slurm_config
  
#- name: Template the second interface
#  template: src=ifcfg_eth1 dest=/etc/sysconfig/network-scripts/ifcfg-{{eth1_name}} mode=0644 backup=no
#  register: config_second_interface
  
- name: Set default route
  lineinfile:
    path: /etc/sysconfig/network
    regexp: ^GATEWAY
    line: "GATEWAY={{main_gateway}}"
    create: yes
    state: present
  register: default_route
  
- name: Set internal interface defroute to no
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{bridge0_name | default('br0')}}
    regexp: ^DEFROUTE
    line: "DEFROUTE=no"
    create: yes
    state: present
  register: defroute_internal
  
#- name: Install nmcli requirements
#  yum:
#    name: "{{item}}"
#    state: present
#  with_items:
#    - NetworkManager-glib
#    - NetworkManager-tui
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Scientific'
  
#- name: Install nmcli requirements DNF
#  dnf:
#    name: "{{item}}"
#    state: present
#  with_items:
#    - NetworkManager-glib
#    - NetworkManager-tui
#  when: ansible_distribution == 'Fedora'
  
#- name: Set static IP for external bridge
#  nmcli:
#    conn_name: "{{bridge1_name | default('br1')}}"
#    ifname: "{{bridge1_name | default('br1')}}"
#    type: bridge
#    ip4: "{{eth1}}/{{netmask_external}}"
#    state: present
    
- name: Template the external bridge
  template: src=ifcfg_bridge dest=/etc/sysconfig/network-scripts/ifcfg-{{bridge1_name | default('br1')}} mode=0644 backup=no
  register: config_second_bridge
  
#- name: Restart network if needed
#  service:
#    name: network
#    state: restarted
#  when: config_first_interface.changed or config_second_interface.changed or default_route.changed

- name: Restart network if required
  service:
    name: network
    state: restarted
  when: default_route.changed or config_second_bridge.changed or defroute_internal.changed

...
