---

# This script installs independent software, mostly for convenience

- name: Disable yum-cron on SL
  yum: name=SL_yum-cron_no_automated_apply_updates state=present
  when: ansible_distribution == 'Scientific'
  
- name: Refresh apt cache on Ubuntu systems
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'

  #Install 'common to all' packages
- name: Install common packages on RedHat based OS
  yum: name={{item}} state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Scientific'
  with_items: "{{common_packages_redhat}}"
- name: Install common packages on Fedora
  dnf: name={{item}} state=present
  when: ansible_distribution == 'Fedora'
  with_items: "{{common_packages_redhat}}"
- name: Install common packages on Ubuntu
  apt: name={{item}} state=present
  when: ansible_distribution == 'Ubuntu'
  with_items: "{{common_packages_ubuntu}}"

...
