---

- include: ../../../playbooks/load_config.yml

#Set up the client ntp synch side

- name: Install ntp on RedHat based OS
  yum: name=ntp state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Scientific'
- name: Install ntp on Fedora
  dnf: name=ntp state=present
  when: ansible_distribution == 'Fedora'
- name: Install ntp on Ubuntu
  apt: name=ntp state=present
  when: ansible_distribution == 'Ubuntu'

- name: Template the ntp client config
  template: src=ntp-client.conf dest=/etc/ntp.conf owner=root mode=0644 backup=yes
  notify: Restart ntp client
  
- name: Enable and start ntp
  service: name={{ntpname[ansible_distribution]}} state=started enabled=yes
  notify: Sync time manually

...
