---

openmpiinfo:
  version: 3.1.0
  url: https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.0.tar.gz
  filename: openmpi-3.1.0.tar.gz
  prefix: /opt/openmpi
  flags: "--enable-mpi-thread-multiple"
openmpi_requirements_redhat:
  - flex
  - flex-devel
openmpi_requirements_ubuntu:
  - flex

...
