---

- name: Install ganglia per yum
  yum: name={{item}} state=present
  with_items: "{{ganglia_packages}}"
  
  #Copy config files
- name: Copy gmetad.conf
  template: src=gmetad.conf dest=/etc/ganglia/gmetad.conf owner=root mode=0644 backup=yes
  register: gmetad_config
- name: Template gmond.conf
  template: src=gmond.conf dest=/etc/ganglia/gmond.conf owner=root mode=0644 backup=yes
  register: gmond_config
- name: Copy ganglia.conf for httpd
  copy: src=ganglia.conf dest=/etc/httpd/conf.d/ganglia.conf mode=0644 backup=yes
  register: ganglia_conf_httpd
  
- name: Set correct ownership for ganglia rrds
  file: path=/var/lib/ganglia/rrds state=directory owner=ganglia group=ganglia recurse=yes
  
- name: Restart httpd if needed
  service: name=httpd state=restarted
  when: ganglia_conf_httpd.changed
- name: Restart gmond if changed
  service: name=gmond state=restarted
  when: gmond_config.changed
- name: Restart gmetad if changed
  service: name=gmetad state=restarted
  when: gmetad_config.changed

...
