---

autofs_packages_ubuntu:
  - autofs
  - rpcbind
  - libnfsidmap2
autofs_packages_redhat:
  - autofs
  - rpcbind
  - libnfsidmap
  - nfs-utils
common_packages_redhat:
  - htop
  - iotop
  - net-tools
  - pciutils
  - screen
  - traceroute
common_packages_ubuntu:
  - htop
  - iotop
  - net-tools
  - screen
  - traceroute
infiniband_packages_redhat:
  - ibutils
  - infiniband-diags
  - libibverbs
  - libibverbs-utils
  - libibverbs-devel
  - libmlx4
  - libmlx5
  - librdmacm
  - librdmacm-utils
  - opensm
  - perftest
  - qperf
  - rdma
infiniband_packages_ubuntu:
  - ibutils
  - ibverbs-utils
  - infiniband-diags
  - libibverbs1
  - libmlx4-1
  - libmlx5-1
  - librdmacm1
  - perftest
  - qperf
  - rdmacm-utils

...
