---

# Various information necessary for installation/compilation
# TODO: Flatten
slurminfo:
  filename: slurm-17-11-7-1.tar.gz
  extracted_filename: slurm-slurm-17-11-7-1
  prefix: /opt/slurm
  statedir: /var/run/slurm
  sysconfdir: /etc/slurm
  version: 17.11.7
  url: https://github.com/SchedMD/slurm/archive/slurm-17-11-7-1.tar.gz
  
# The default user to be used by various slurm parts
# slurmd will always run as root though
slurm_daemon_user: slurm

# On a per host basis (or group) in the inventory:
# controller (slurmctld) + database (slurmdbd) can run on one node
# compute (slurmd) may only run alone on a system
slurm_roles: "controller database compute"

...
