---

# The complet setup with the suggested or needed role ordering

# These roles can be applied anytime, hence all hosts
- hosts: all
  roles:
    - { role: ssh-management }

- hosts: home_server
  roles:
    - { role: fs, nfs_export: "{{home_export}}" }
- hosts: app_server
  roles:
    - { role: fs, nfs_export: "{{app_export}}" }

- hosts: opensm
  roles:
    - { role: opensm }

- hosts: common:!frontend
  roles:
    - { role: ntp_client }

- hosts: webserver:!frontend
  roles:
    - { role: webserver_system }

- hosts: webserver
  roles:
    - { role: webserver }
    - { role: ganglia, vars: {ganglia_role: gmetad} }
    
  #For software and slurm
- hosts: compute login frontend
  roles:
    - { role: software }
    - { role: andrewrothstein.anaconda }
- hosts: frontend
  roles:
    - { role: slurm_frontend }
- hosts: compute
  roles:
    - { role: compute }
    - { role: ganglia, vars: {ganglia_role: gmond} }
- hosts: gpu
  roles:
    - { role: gpu }
    
- hosts: login
  roles:
    - { role: login }
    
...
