---

- hosts: home_server
  roles:
    - { role: fs, nfs_export: "{{home_export}}" }
- hosts: app_server
  roles:
    - { role: fs, nfs_export: "{{app_export}}" }

- hosts: opensm
  roles:
    - { role: opensm }

- hosts: common
  roles:
    - { role: common }

- hosts: common:!frontend
  roles:
    - { role: ntp_client }

- hosts: webserver:!frontend
  roles:
    - { role: webserver_system }

- hosts: webserver
  roles:
    - { role: webserver }
    
  #For software and slurm
- hosts: slurmdbd
  roles:
    - { role: mariadb }
- hosts: compute login frontend
  roles:
    - { role: software }
- hosts: slurmdbd
  roles:
    - { role: slurmdbd }
- hosts: frontend
  roles:
    - { role: slurmctld }
- hosts: compute
  roles:
    - { role: compute }
    
- hosts: login
  roles:
    - { role: login }
    
#- hosts: gpucompute
#  roles:
#    - { role: gpu }
    
...
