---

- hosts: frontend
  roles:
    - { role: frontend }
    - { role: cobbler_server }
    - { role: webserver }
    - { role: software }
    - { role: andrewrothstein.anaconda }
    - { role: ssh-management }

...
