---

- hosts: frontend
  roles:
    - { role: frontend }
    - role: firewalld
      tags: ['is_bridged']
    - { role: cobbler_server }
    - { role: webserver }
    - { role: software }
    - { role: andrewrothstein.anaconda }
    - { role: slurm_frontend }
    - { role: ganglia, vars: {ganglia_role: gmetad} }
    - { role: ssh-management }

...
