---

- hosts: frontend login compute slurmdbd
  roles:
    - role: build-environment
    - role: munge
    - role: slurm
    
#- hosts: frontend
#  roles:
#    - role: slurm
#      tags: ['slurmctld']

#- hosts: slurmdbd
#  roles:
#    - role: slurm
#      tags: ['slurmdbd']

#- hosts: compute
#  roles:
#    - role: slurm

...
