---

  #For a complete software setup
- hosts: compute login frontend
  roles:
    - { role: software }
- hosts: frontend
  roles:
    - { role: slurm_frontend }
- hosts: compute
  roles:
    - { role: compute }
- hosts: login
  roles:
    - { role: login }

...
