---

  #For a complete software setup
- hosts: compute login frontend
  roles:
    - { role: software }
    - { role: andrewrothstein.anaconda }
- hosts: frontend
  roles:
    - { role: slurm_frontend }
- hosts: compute
  roles:
    - { role: compute }
    - { role: ganglia, vars: {ganglia_role: gmond} }
- hosts: login
  roles:
    - { role: login }
    - { role: ganglia, vars: {ganglia_role: gmond} }

...
