---

- hosts: login compute frontend home_server
  
  tasks:
    - include: load_groups.yml
    - include: load_users.yml

    - name: Update all user groups
      group:
        name: "{{cluster_groups[item].name}}"
        gid: "{{item}}"
        state: present
        system: no
      with_items: "{{cluster_groups}}"
      no_log: True

    - name: Update all cluster users
      user:
        name: "{{cluster_users[item]['passwd'].name}}"
        uid: "{{item}}"
        groups: "{{cluster_users[item]['passwd'].groups}}"
        group: "{{cluster_users[item]['passwd'].group}}"
        password: "{{cluster_users[item]['passwd'].password}}"
        home: "{{cluster_users[item]['passwd'].homepath}}"
        shell: "{{cluster_users[item]['passwd'].shellpath}}"
        createhome: no
        state: present
        system: no
      with_items: "{{cluster_users}}"
      no_log: True

- hosts: home_server

  tasks:
    - include: load_users.yml
    
    - name: Create user homes
      file: 
        path: "{{home_export}}/{{cluster_users[item]['passwd'].name}}"
        state: directory
        owner: "{{cluster_users[item]['passwd'].name}}"
        group: "{{cluster_users[item]['passwd'].group}}"
#        mode: "{{cluster_users[item]['passwd'].permissions}}"
        mode: 0750
      with_items: "{{cluster_users}}"
      no_log: True
      
    - name: Create .ssh dir
      file:
        path: "{{home_export}}/{{cluster_users[item]['passwd'].name}}/.ssh"
        state: directory
        owner: "{{cluster_users[item]['passwd'].name}}"
        group: "{{cluster_users[item]['passwd'].group}}"
        mode: 0700
      with_items: "{{cluster_users}}"
      no_log: True

    - name: Generate ssh keys
      shell: ssh-keygen -t ecdsa -f "{{home_export}}/{{cluster_users[item]['passwd'].name}}/.ssh/id_ecdsa" -P ""
      args:
        creates: "{{home_export}}/{{cluster_users[item]['passwd'].name}}/.ssh/id_ecdsa"
      become: true
      become_user: "{{cluster_users[item]['passwd'].name}}"
      with_items: "{{cluster_users}}"
      no_log: True
      
    - name: Slurp the public keys
      slurp:
        src: "{{home_export}}/{{cluster_users[item]['passwd'].name}}/.ssh/id_ecdsa.pub"
      with_items: "{{cluster_users}}"
      register: slurped_public_key
      no_log: True
      
    - name: Authorize the keys
      authorized_key:
        user: "{{cluster_users[item.item]['passwd'].name}}"
        state: present
        key: "{{item.content | b64decode}}"
        path: "{{home_export}}/{{cluster_users[item.item]['passwd'].name}}/.ssh/authorized_keys"
      with_items: "{{slurped_public_key.results}}"
      no_log: True

...
