---

#################################################
## Update known hosts in cobbler from
## ansible hosts file and then issue the command
##    cobbler system add 
## 
#################################################

- hosts: frontend
    
  tasks:
    - include: load_config.yml
      
      #####Create cobbler entries
    - name: Get cobbler system list
      command: cobbler system list
      register: cobbler_systems
      
      #Has to be done this way, since cobbler fails if system already exists
    - name: Add cobbler system if new
      command: cobbler system add --name="{{item}}" --profile="{{hostvars[item]['profile']}}"
      with_items: "{{groups['common']}}"
      when: "item not in cobbler_systems.stdout"
      
    - name: Always edit system objects
      command: cobbler system edit --name="{{item}}" --hostname="{{item}}" --dns-name="{{item}}.{{domain}}" --ip-address="{{hostvars[item]['eth0']}}" --netmask="{{netmask_internal_long}}" --gateway={{eth0}} --static=0 --interface={{hostvars[item]['eth0_name']}} --profile="{{hostvars[item]['profile']}}" --mac="{{hostvars[item]['mac0']}}" --management=true
      with_items: "{{groups['common']}}"
            
    - name: Update cobbler guest system entries if needed
      command: cobbler system edit --name={{item}} --virt-auto-boot={{virtAutoBoot}} --virt-cpus={{virtCPUs}} --virt-disk-driver="<<inherit>>" --virt-file-size={{virtDiskSize}} --virt-ram={{virtRam}} --virt-type={{virtType}} --virt-pxe={{virtPxeBoot}}
      with_items: "{{groups['guests']}}"
      when: "item not in cobbler_systems.stdout"
      
      
      ######Add network interfaces
    - name: Add second interfaces to webserver
      command: cobbler system edit --name="{{item}}" --interface="{{hostvars[item]['eth1_name']}}" --ip-address="{{hostvars[item]['eth1']}}" --netmask="{{netmask_external_long}}" --mac="{{hostvars[item]['mac1']}}"
      with_items: "{{groups['webserver']}}"
      when: item not in cobbler_systems.stdout
      
    - name: Add second interfaces to login nodes
      command: cobbler system edit --name="{{item}}" --interface="{{hostvars[item]['eth1_name']}}" --ip-address="{{hostvars[item]['eth1']}}" --netmask="{{netmask_external_long}}" --mac="{{hostvars[item]['mac1']}}"
      with_items: "{{groups['login']}}"
      when: item not in cobbler_systems.stdout
      
#    - name: Add infiniband interfaces to common nodes
#      command: cobbler system edit --name="{{item}}" --interface=ib0 --ip-address="{{hostvars[item]['ibip']}}" --netmask="{{netmask_internal_long}}" --mac="{{hostvars[item]['ipmac']}}"
#      with_items: "{{groups['common']}}"
#      when: "'{{item}}' not in cobbler_systems.stdout" 
      
...
