---

#################################################
## Update known hosts in cobbler from
## ansible hosts file and then issue the command
##    cobbler system add 
## 
#################################################

- hosts: frontend
    
  tasks:
    - include: load_config.yml
      
      #####Create cobbler entries
    - name: Get cobbler system list
      command: cobbler system list
      register: cobbler_systems
      
      #Has to be done this way, since cobbler fails if system already exists
    - name: Add cobbler system if new
      command: cobbler system add --name="{{item}}" --profile="{{hostvars[item]['profile']}}"
      with_items: "{{groups['common']}}"
      when: item not in cobbler_systems.stdout
      
    - name: Update cobbler system objects
#      command: cobbler system edit --name="{{item}}" --hostname="{{item}}" --dns-name="{{item}}.{{domain}}" --gateway="{{eth0}}" --static=0 --profile="{{hostvars[item]['profile']}}" --interface="{{hostvars[item]['eth0_name'] | default('eth0')}}" --mac="{{hostvars[item]['mac0']}}" --management=true --ip-address="{{hostvars[item]['eth0']}}" --netmask="{{netmask_internal_long}}" --kopts="{{hostvars[item]['kopts'] | default('')}}"
      command: cobbler system edit --name="{{item}}" --hostname="{{item}}" --dns-name="{{item}}.{{domain}}" --gateway="{{eth0}}" --static=0 --profile="{{hostvars[item]['profile']}}" --interface="{{hostvars[item]['eth0_name'] | default('eth0')}}" --mac="{{hostvars[item]['mac0']}}" --management=true --interface-type=bridge_slave --interface-master="{{hostvars[item]['bridge0_name'] | default('br0')}}" --kopts="{{hostvars[item]['kopts'] | default('')}}"
      with_items: "{{groups['common']}}"
      
    - name: Bridge first interface
      command: cobbler system edit --name="{{item}}" --interface="{{hostvars[item]['bridge0_name'] | default('br0')}}" --bridge-opts="stp=no" --ip-address="{{hostvars[item]['eth0']}}" --netmask="{{netmask_internal_long}}"
      with_items: "{{groups['common']}}"
      
      
      ######Add network interfaces
      # Even if frontend is part of webserver group, since cobbler runs on
      # the frontend, this won't ever take effect!
    - name: Add second interfaces to login and webserver nodes
#      command: cobbler system edit --name="{{item}}" --interface="{{hostvars[item]['eth1_name'] | default('eth1')}}" --mac="{{hostvars[item]['mac1']}}" --ip-address="{{hostvars[item]['eth1']}}" --netmask="{{netmask_internal_long}}"
      command: cobbler system edit --name="{{item}}" --interface="{{hostvars[item]['eth1_name'] | default('eth1')}}" --mac="{{hostvars[item]['mac1']}}" --interface-type=bridge_slave --interface-master="{{hostvars[item]['bridge1_name'] | default('br1')}}"
      with_items: 
        - "{{groups['login']}}"
        - "{{groups['webserver']}}"
      
    - name: Bridge second interface for login and webserver nodes
      command: cobbler system edit --name="{{item}}" --interface="{{hostvars[item]['bridge1_name'] | default('br1')}}" --bridge-opts="stp=no" --ip-address="{{hostvars[item]['eth1']}}" --netmask="{{netmask_internal_long}}"
      with_items: 
        - "{{groups['login']}}"
        - "{{groups['webserver']}}"
      
#    - name: Add infiniband interfaces to common nodes
#      command: cobbler system edit --name="{{item}}" --interface="{{hostvars[item]['ibname'] | default('ib0')}}" --ip-address="{{hostvars[item]['ibip']}}" --netmask="{{netmask_internal_long}}" --mac="{{hostvars[item]['ipmac']}}"
#      with_items: "{{groups['common']}}"
#      when: hostvars[item]['ibtype'] != 'none'
      
...
