---

- hosts: frontend
  pre_tasks:
    - include: load_config.yml
    - set_fact:
        zabbix_server_name: "{{ groups['frontend'][0] }}"
        zabbix_server_database: mysql
        zabbix_server_database_long: mysql
#        zabbix_server_hostname: "{{ groups['frontend'][0] }}"  #default: inventory_hostname
        zabbix_server_listenport: 10051
        zabbix_server_dbname: "{{ zabbix_db_config['dbname'] | default('zabbix') }}"
        zabbix_server_dbhost: "{{ groups['frontend'][0] }}"
        zabbix_server_dbuser: "{{ zabbix_db_config['username'] | default('zabbix') }}"
        zabbix_server_dbpassword: "{{ zabbix_db_config['password'] }}"
        zabbix_server_dbport: 2230
        zabbix_database_creation: True
        zabbix_database_sqlload: True
#        zabbix_server_dbencoding: utf8 #default value
#        zabbix_server_dbcollation: utf8_bin #default value
        zabbix_server_tlscafile:
        zabbix_server_tlscrlfile:
        zabbix_server_tlscertfile: "{{ssl_files['self']['cert']['dest'] | default('/etc/pki/tls/certs/apache_self.crt') }}"
        zabbix_server_tlskeyfile: "{{ssl_files['self']['key']['dest'] | default('/etc/pki/tls/private/apache_self.key') }}"
        zabbix_server_mysql_login_host: "{{groups['slurmdbd'][0] | default(groups['frontend'][0])}}"
        zabbix_server_mysql_login_user: "root"
        zabbix_server_mysql_login_password: "{{slurmdbd_config['rootpass']}}"
  roles:
    - { role: zabbix-server }

...
