---

- include: ../../../playbooks/load_config.yml
  
  #Install kvm
- name: Install kvm YUM
  yum: name={{item}} state=present
  with_items: "{{kvm_packages_redhat}}"
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'
- name: Install kvm DNF
  yum: name={{item}} state=present
  with_items: "{{kvm_packages_redhat}}"
  when: ansible_distribution == 'Fedora'

  #Now setup bridges in/out interfaces
- name: Install bridging tools
  yum: name=bridge-utils state=present
  
- name: Template internal bridge
  template: src=bridge_internal_config dest=/etc/sysconfig/network-scripts/ifcfg-{{bridge0_name | default('br0')}} mode=0644 backup=yes
  notify: Restart network and dnsmasq
- name: Template internal interface
  template: src=internal_config dest=/etc/sysconfig/network-scripts/ifcfg-{{eth0_name | default('eth0')}} mode=0644 backup=yes
  notify: Restart network
- name: Template external bridge
  template: src=bridge_external_config dest=/etc/sysconfig/network-scripts/ifcfg-{{bridge1_name | default('br1')}} mode=0644 backup=yes
  notify: Restart network
- name: Template external interface
  template: src=external_config dest=/etc/sysconfig/network-scripts/ifcfg-{{eth1_name | default('eth1')}} mode=0644 backup=yes
  notify: Restart network
  
- name: Start and enable libvirtd
  service:
    name: "{{libvirt_daemon[ansible_os_family]}}"
    state: started
    enabled: yes
  
...
