---

#- name: Template the nvidia driver repo
#  template:
#    src: nvidia-Fedora.repo
#    dest: /etc/yum.repos.d/nvidia-Fedora.repo
    
- name: Install kernel files
  dnf:
    name: "{{item}}"
    state: present
  loop: "{{ kernel_packages_redhat }}"
    
- name: Installing the Nvidia driver packages
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ nvidia_main_packages }}"
  notify: Nvidia driver update

# Cuda installation
#- name: Template the Fedora cuda repo
#  template:
#    src: cuda_Fedora.repo
#    dest: /etc/yum.repos.d/cuda.repo
    
- name: Install cuda
  dnf:
    name: "{{cuda_toolkit_package}}"
    state: present
  notify: Cuda update message

...
