---

#- name: Template the cuda repo
#  template:
#    src: cuda.repo
#    dest: /etc/yum.repos.d/cuda.repo

- name: Install kernel files
  yum:
    name: "{{item}}"
    state: present
  loop: "{{ kernel_packages_redhat }}"
    
- name: Install cuda
  yum:
    name: cuda
    state: present
  notify: Cuda update message

...
